version: '3.7'

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:${KIBANA_VERSION}
    container_name: kibana
    volumes:
      - ./resources/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro,Z
    ports:
      - "5601:5601"
    environment:
      KIBANA_SYSTEM_PASSWORD: N4xaRdT5i5zRl33Wcd2y
    networks:
      - elk
networks:
  elk:
    driver: bridge

volumes:
  setup:
  resources:
