version: '3.7'

services:
  logstash:
    image: docker.elastic.co/logstash/logstash:${LOGSTASH_VERSION}
    container_name: logstash
    volumes:
      - ./resources/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro,Z
      - ./resources/pipeline:/usr/share/logstash/pipeline:ro,Z
    ports:
      - "5044:5044"
      - "50000:50000/tcp"
      - "50000:50000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: -Xms256m -Xmx256m
      LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD:-}
    networks:
      - elk
    ulimits:
      memlock:
        soft: -1
        hard: -1

networks:
  elk:
    driver: bridge

volumes:
  resources:
    driver: local
